"""initial schema: users, audit_log, exceptions, reconciliation_runs, webhook_events

Revision ID: 14faee91f3c0
Revises: 
Create Date: 2026-09-04 03:20:06.843631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14faee91f3c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('rule_used', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_transaction_id'), 'audit_log', ['transaction_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('exception_type', sa.String(), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('date_difference_days', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_evidence', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_payment_id'), 'exceptions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_exceptions_transaction_id'), 'exceptions', ['transaction_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_is_latest'), 'reconciliation_runs', ['is_latest'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id', name='uq_webhook_event_id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_razorpay_event_id'), 'webhook_events', ['razorpay_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_razorpay_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reconciliation_runs_is_latest'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_exceptions_transaction_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_payment_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_audit_log_transaction_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
